### ISSUE TITLE
Ain't compilin'

### ISSUE THREAD

**Issue by redcubie** [espilioto/NoritakeVFD-winforms#1]
I wanted to use my ba63-1 but when I started to compile the code, it gives out like 5 errors

**Comment by espilioto** [comment]
Damn, now that's a throwback.
Let's see if I can figure out what's going on, I'll get back to you soon™.

**Comment by espilioto** [comment]
Just copy the ddl in your bin/debug dir and rebuild.
[CoreAudioApi.zip](https://github.com/espilioto/NoritakeVFD-winforms/files/1798338/CoreAudioApi.zip)

Not to mention that you could just delete all the audio related code along with the reference, since I never achieved the VU meter effect I was after.

![img_20180309_224613](https://user-images.githubusercontent.com/8510006/37229239-0b86a9ca-23ec-11e8-9ba8-8c7c001aa8a7.jpg)

**Comment by redcubie** [comment]
Thank You!!!
